- hosts: all
  become: yes
  tasks:

  - name: Install httpd
    ansible.builtin.dnf:
      name: httpd
      state: present

  - name: Start httpd
    ansible.builtin.service:
      name: httpd
      state: started
      enabled: yes

  - name: Create users jisoo, lisa, rose, jennie
    ansible.builtin.user:
       name: "{{ item }}"
       state: present
    loop:
      - jisoo
      - lisa
      - jennie
      - rose
    
